name: Runs flake8 on PR

on:Â [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: tayfun/flake8-your-pr@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
